apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- np-test-48/np-test-48-allow-prometheus-metrics.yaml
- np-test-48/np-test-48-allow-same-namespace.yaml
- np-test-48/np-test-48-deny-all-egress.yaml
- np-test-48/np-test-48-deny-all-ingress.yaml
