apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- np-test-56/np-test-56-allow-prometheus-metrics.yaml
- np-test-56/np-test-56-allow-same-namespace.yaml
- np-test-56/np-test-56-deny-all-egress.yaml
- np-test-56/np-test-56-deny-all-ingress.yaml
