apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    network-policy.permission-binder.io/template: allow-prometheus-metrics.yaml
    network-policy.permission-binder.io/template-path: networkpolicies/templates/allow-prometheus-metrics.yaml
    network-policy.permission-binder.io/template-version: HEAD
  name: pbo9-np-test-59-a-allow-prometheus-metrics
  namespace: pbo9-np-test-59-a
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-monitoring
    - namespaceSelector:
        matchLabels:
          name: openshift-user-workload-monitoring
  podSelector: {}
  policyTypes:
  - Ingress
